language: node_js
dist: trusty
addons:
  apt:
    packages:
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
# allow headful tests
before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  -  npm start &
cache:
  yarn: true
  directories:
    - node_modules

cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
